# 🔧 [DEVELOPMENT-TOOL]
# Development configuration file
# Codespace Configuration
name: Turbo Trading Bot Codespace
description: Complete trading bot development environment

# Use the official Node.js devcontainer
image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye

# Post-creation command
onCreateCommand: |
  echo "Setting up Turbo Trading Bot environment..."
  npm install
  chmod +x scripts/*.sh
  chmod +x .devcontainer/setup.sh
  .devcontainer/setup.sh

# Update content command
updateContentCommand: |
  npm install
  npm run build

# Post-start command
postStartCommand: |
  echo "🚀 Turbo Trading Bot is ready!"
  echo "📊 Run 'npm run dev' to start development"
  echo "🔧 Configure .env with your API keys"

# Extensions to install
extensions:
  - ms-vscode.vscode-typescript-next
  - ms-python.python
  - bradlc.vscode-tailwindcss
  - esbenp.prettier-vscode
  - ms-vscode.vscode-json
  - GitHub.copilot
  - ms-kubernetes-tools.vscode-kubernetes-tools

# Port forwarding
forwardPorts:
  - 3000  # Bot API
  - 8080  # Grafana
  - 9090  # Prometheus
  - 3001  # Frontend

# VS Code settings
settings:
  terminal.integrated.defaultProfile.linux: bash
  typescript.preferences.includePackageJsonAutoImports: auto
  editor.formatOnSave: true

# Environment variables
env:
  NODE_ENV: development
  CODESPACE: true
