/**
 * 🔧 [SHARED-INFRASTRUCTURE]
 * Shared infrastructure component
 */
/**
 * 🔧 [SHARED-INFRASTRUCTURE]
 * Shared trading infrastructure component
 */
/**
 * 🚀 MINIMAL BOT FOR GRAFANA TESTING
 * Only starts Prometheus metrics server with sample data
 */

import express from 'express';
import * as promClient from 'prom-client';

// Create sample metrics for Grafana dashboard
const portfolioValue = new promClient.Gauge({
  name: 'trading_bot_portfolio_value',
  help: 'Current portfolio value in USD'
});

const totalPnL = new promClient.Gauge({
  name: 'trading_bot_total_pnl',
  help: 'Total profit and loss in USD'
});

const botStatus = new promClient.Gauge({
  name: 'trading_bot_status',
  help: 'Bot status (1 = online, 0 = offline)'
});

const winRate = new promClient.Gauge({
  name: 'trading_bot_win_rate',
  help: 'Win rate percentage (0-1)'
});

const uptime = new promClient.Gauge({
  name: 'trading_bot_uptime',
  help: 'Bot uptime in seconds'
});

const totalTrades = new promClient.Counter({
  name: 'trading_bot_total_trades',
  help: 'Total number of trades executed',
  labelNames: ['symbol', 'side']
});

const signalsGenerated = new promClient.Counter({
  name: 'trading_bot_signals_generated',
  help: 'Number of signals generated by strategy',
  labelNames: ['strategy', 'signal_type']
});

const signalsByStrategy = new promClient.Gauge({
  name: 'trading_bot_signals_by_strategy',
  help: 'Signals count by strategy',
  labelNames: ['strategy']
});

const dailyPnL = new promClient.Gauge({
  name: 'trading_bot_daily_pnl',
  help: 'Daily profit and loss in USD'
});

const activePairs = new promClient.Gauge({
  name: 'trading_bot_active_pairs',
  help: 'Number of active trading pairs'
});

const cpuUsage = new promClient.Gauge({
  name: 'trading_bot_cpu_usage',
  help: 'CPU usage percentage'
});

const memoryUsage = new promClient.Gauge({
  name: 'trading_bot_memory_usage',
  help: 'Memory usage in bytes'
});

const tradingCycleDuration = new promClient.Histogram({
  name: 'trading_bot_trading_cycle_duration',
  help: 'Duration of trading cycle in milliseconds',
  buckets: [10, 50, 100, 500, 1000, 5000]
});

const marketDataLatency = new promClient.Histogram({
  name: 'trading_bot_market_data_latency',
  help: 'Market data latency in milliseconds',
  buckets: [1, 5, 10, 25, 50, 100]
});

const orderExecutionTime = new promClient.Histogram({
  name: 'trading_bot_order_execution_time',
  help: 'Order execution time in milliseconds',
  buckets: [10, 25, 50, 100, 250, 500]
});

class MinimalBotForGrafana {
  private app: express.Application;
  private startTime: number;

  constructor() {
    this.app = express();
    this.startTime = Date.now();
    this.setupRoutes();
    this.generateSampleData();
  }

  private setupRoutes() {
    // Prometheus metrics endpoint
    this.app.get('/metrics', async (req, res) => {
      try {
        res.set('Content-Type', promClient.register.contentType);
        const metrics = await promClient.register.metrics();
        res.end(metrics);
      } catch (error) {
        res.status(500).end(error);
      }
    });

    // Health check endpoint
    this.app.get('/health', (req, res) => {
      res.json({
        status: 'healthy',
        uptime: Math.floor((Date.now() - this.startTime) / 1000),
        timestamp: new Date().toISOString()
      });
    });

    // Bot status endpoint
    this.app.get('/status', (req, res) => {
      res.json({
        bot_status: 'ONLINE',
        portfolio_value: 50000 + Math.random() * 10000,
        total_pnl: 2500 + Math.random() * 1000,
        win_rate: 0.65 + Math.random() * 0.1,
        active_strategies: ['RSITurbo', 'MACrossover', 'SuperTrend', 'MomentumPro'],
        uptime: Math.floor((Date.now() - this.startTime) / 1000)
      });
    });
  }

  private generateSampleData() {
    // Update metrics every 5 seconds with realistic trading data
    setInterval(() => {
      const currentTime = Date.now();
      const uptimeSeconds = Math.floor((currentTime - this.startTime) / 1000);

      // Portfolio metrics with some volatility
      const basePortfolio = 50000;
      const portfolioVariation = Math.sin(currentTime / 60000) * 5000 + Math.random() * 2000;
      portfolioValue.set(basePortfolio + portfolioVariation);

      const pnlBase = 2500;
      const pnlVariation = Math.sin(currentTime / 120000) * 1000 + Math.random() * 500;
      totalPnL.set(pnlBase + pnlVariation);

      dailyPnL.set(250 + Math.sin(currentTime / 86400000) * 200 + Math.random() * 100);

      // Bot status and performance
      botStatus.set(1); // Always online
      winRate.set(0.65 + Math.sin(currentTime / 300000) * 0.05 + Math.random() * 0.02);
      uptime.set(uptimeSeconds);
      activePairs.set(3 + Math.floor(Math.random() * 3)); // 3-5 pairs

      // System metrics
      cpuUsage.set(15 + Math.random() * 20); // 15-35% CPU
      memoryUsage.set(800000000 + Math.random() * 200000000); // 800MB-1GB

      // Strategy signals (cumulative)
      const strategies = ['RSITurbo', 'MACrossover', 'SuperTrend', 'MomentumPro', 'EnhancedRSI'];
      strategies.forEach(strategy => {
        if (Math.random() > 0.7) { // 30% chance to generate signal
          const signalType = Math.random() > 0.5 ? 'BUY' : 'SELL';
          signalsGenerated.inc({ strategy, signal_type: signalType });
        }
        
        // Update strategy distribution
        signalsByStrategy.set({ strategy }, 10 + Math.random() * 50);
      });

      // Trading activity
      const symbols = ['BTCUSDT', 'ETHUSDT', 'ADAUSDT'];
      if (Math.random() > 0.8) { // 20% chance for trade
        const symbol = symbols[Math.floor(Math.random() * symbols.length)];
        const side = Math.random() > 0.5 ? 'BUY' : 'SELL';
        totalTrades.inc({ symbol, side });
      }

      // Performance histograms
      tradingCycleDuration.observe(50 + Math.random() * 200);
      marketDataLatency.observe(5 + Math.random() * 15);
      orderExecutionTime.observe(25 + Math.random() * 75);

    }, 5000); // Update every 5 seconds
  }

  async start() {
    const PORT = 9090;
    
    return new Promise<void>((resolve) => {
      this.app.listen(PORT, () => {
        console.log('🚀 Minimal Trading Bot for Grafana started!');
        console.log(`📊 Prometheus metrics: http://localhost:${PORT}/metrics`);
        console.log(`🔍 Health check: http://localhost:${PORT}/health`);
        console.log(`📈 Bot status: http://localhost:${PORT}/status`);
        console.log('✅ Ready for Grafana dashboard connection!');
        resolve();
      });
    });
  }
}

// Start the minimal bot
const bot = new MinimalBotForGrafana();
bot.start().catch(console.error);

// Graceful shutdown
process.on('SIGINT', () => {
  console.log('🛑 Shutting down...');
  process.exit(0);
});

process.on('SIGTERM', () => {
  console.log('🛑 Shutting down...');
  process.exit(0);
});
